[package]
name = "dandi-zarr-checksum"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.2.8", default-features = false, features = ["derive", "std", "suggestions", "wrap_help"] }
hex = "0.4.3"
log = "0.4.17"
md-5 = "0.10.1"
stderrlog = "0.5.3"
thiserror = "1.0.31"
walkdir = "2.3.2"

[dev-dependencies]
fs_extra = "1.2.0"
rstest = "0.15.0"
tempfile = "3.3.0"
